---
- name: Install and configure Amazon EC2Launch Service 
  hosts: all
  become: false
  gather_facts: true

  tasks:
    - name: Create the EC2Launch destination directory
      win_file:
       path: C:\Software\EC2Launch
       state: directory

    - name: Download the EC2Launch Installer 
      win_get_url:
        url: https://s3.amazonaws.com/amazon-ec2launch-v2/windows/amd64/latest/AmazonEC2Launch.msi 
        dest: C:\Software\EC2Launch


    - name: Install the Amazon EC2Launch service
      win_package:
        path: C:\Software\EC2Launch\AmazonEC2Launch.msi
        state: present
        
    - name: Remove installer file from destination
      win_file:
       path: C:\Software\EC2Launch\AmazonEC2Launch.msi
       state: absen
