name: "GitHub Action: Self-Test"

on:
  workflow_dispatch:

env:
  PRODUCT_VERSION: "1.8.6"

jobs:
  setup-packer:
    name: Test `setup-packer`
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0


      - name: Print `$PATH` for `packer`
        run: which packer

      - name: Print `packer` version
        run: packer version

      - name: Run `packer fmt`
        run: packer fmt -check "./home/ami-windows.pkr.hcl"

      - name: Print `packer` version
        run: packer version
