name: "GitHub Action: Self-Test"

on:
  workflow_dispatch:

env:
  PRODUCT_VERSION: "1.8.6"

jobs:
  setup-packer:
    name: Test `setup-packer`
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0

      - name: Run `packer fmt`
        run: packer fmt "./home/ami-windows.pkr.hcl"
  
      - name: Run `packer init`
        run: packer init "./home/ami-windows.pkr.hcl"
        
      - name: Run `packer validate`
        run: packer validate "./home/ami-windows.pkr.hcl"

      #- name: Run `packer build`
         #run: packer build -var "password=${{ secrets.PASSWORD }}" "./home/ami-windows.pkr.hcl"  

 
